version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: cqrs-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: api-green
    command: >
      uvicorn app_cqrs.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    volumes:
      - ./src:/app/src
    working_dir: /app/src
    ports:
      - "8001:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017

volumes:
  mongo_data:
